In [1]:
import dataclasses
import functools
import operator
import pathlib
import warnings

import altair as alt
import geopandas as gpd
import pandas as pd
import pyproj
import shapely
import shapely.plotting

import pitchmark
import pitchmark.osm

In [2]:
METERS_PER_YARD = 0.9144
WGS84_EQUATORIAL_RADIUS = 6_378_137.0  # meters
WGS84_INVERSE_FLATTENING = 298.257_223_563

In [3]:
map_path = pathlib.Path(".") / "augusta_national" / "map.osm"
handler = pitchmark.osm.GolfHandler()
handler.apply_file(map_path)
fc = handler.feature_collection
augusta_national = pitchmark.Course.from_featurecollection(fc)

In [8]:
len(augusta_national.gdf)

204

In [9]:
ch = augusta_national.chart()
ch

alt.Chart(...)

In [12]:
isinstance(ch, alt.Chart)

True

In [13]:
augusta_national.gdf

,name,course_area,ground_cover,geometry
168,woods,general_area,woods,"POLYGON ((-364.377 210.856, -364.295 207.363, ..."
222,rough,general_area,long_grass,"POLYGON ((-399.804 -688.022, -398.869 -692.801..."
158,woods,general_area,woods,"POLYGON ((-167.382 -395.922, -159.639 -418.350..."
138,fairway,general_area,short_grass,"POLYGON ((-106.194 -302.804, -105.249 -314.509..."
135,fairway,general_area,short_grass,"POLYGON ((-181.484 -183.993, -181.413 -186.310..."
...,...,...,...,...
112,tee,teeing_area,short_grass,"POLYGON ((-183.500 -421.879, -177.088 -422.219..."
34,bunkers,bunker,sand,"POLYGON ((-94.679 -80.650, -94.435 -81.656, -9..."
161,woods,general_area,woods,"POLYGON ((-245.263 -280.750, -230.011 -333.381..."
32,bunkers,bunker,sand,"POLYGON ((-179.462 -186.079, -179.370 -186.953..."
31,bunkers,bunker,sand,"POLYGON ((-173.079 -166.866, -173.039 -167.715..."

In [14]:
augusta_national.gdf.crs

<Derived Projected CRS: +proj=tmerc +lon_0=-82.0198831 +lat_0=33.5023672 + ...>
Name: unknown
Axis Info [cartesian]:
- E[east]: Easting (yard)
- N[north]: Northing (yard)
Area of Use:
- undefined
Coordinate Operation:
- name: unknown
- method: Transverse Mercator
Datum: Unknown based on WGS84 ellipsoid
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [15]:
augusta_national.holes

[Hole(hole_number=1, name='Tea Olive', path=<LINESTRING (-82.02 33.502, -82.022 33.504, -82.024 33.504)>),
 Hole(hole_number=2, name='Pink Dogwood', path=<LINESTRING (-82.024 33.505, -82.025 33.502, -82.024 33.501, -82.024 33.5)>),
 Hole(hole_number=3, name='Flowering Peach', path=<LINESTRING (-82.023 33.5, -82.025 33.501, -82.026 33.502)>),
 Hole(hole_number=4, name='Flowering Crab Apple', path=<LINESTRING (-82.026 33.502, -82.028 33.502)>),
 Hole(hole_number=5, name='Magnolia', path=<LINESTRING (-82.029 33.502, -82.028 33.5, -82.028 33.499, -82.027 33.498)>),
 Hole(hole_number=6, name='Juniper', path=<LINESTRING (-82.027 33.499, -82.027 33.5)>),
 Hole(hole_number=7, name='Pampas', path=<LINESTRING (-82.027 33.501, -82.025 33.5, -82.023 33.499)>),
 Hole(hole_number=8, name='Yellow Jasmine', path=<LINESTRING (-82.022 33.499, -82.023 33.502, -82.023 33.503, -82.024 33.504)>),
 Hole(hole_number=9, name='Carolina Cherry', path=<LINESTRING (-82.024 33.504, -82.022 33.502, -82.021 33.502)>),
 Hole(hole_number=10, name='Camellia', path=<LINESTRING (-82.02 33.502, -82.021 33.5, -82.02 33.498)>),
 Hole(hole_number=11, name='White Dogwood', path=<LINESTRING (-82.019 33.499, -82.021 33.496, -82.022 33.495)>),
 Hole(hole_number=12, name='Golden Bell', path=<LINESTRING (-82.022 33.496, -82.023 33.495)>),
 Hole(hole_number=13, name='Azalea', path=<LINESTRING (-82.024 33.494, -82.024 33.496, -82.025 33.497, -82.026 33.497)>),
 Hole(hole_number=14, name='Chinese Fir', path=<LINESTRING (-82.026 33.498, -82.023 33.497, -82.021 33.497)>),
 Hole(hole_number=15, name='Firethorn', path=<LINESTRING (-82.021 33.498, -82.023 33.498, -82.025 33.499, -82.026 33.499)>),
 Hole(hole_number=16, name='Redbud', path=<LINESTRING (-82.026 33.498, -82.026 33.5)>),
 Hole(hole_number=17, name='Nandina', path=<LINESTRING (-82.027 33.5, -82.024 33.499, -82.022 33.499)>),
 Hole(hole_number=18, name='Holly', path=<LINESTRING (-82.022 33.498, -82.021 33.501, -82.021 33.502)>)]

In [16]:
hole_charts = [hole.chart() for hole in augusta_national.holes]

In [17]:
for chart in hole_charts:
    chart.display()

alt.Chart(...)

alt.Chart(...)

alt.Chart(...)

alt.Chart(...)

alt.Chart(...)

alt.Chart(...)

alt.Chart(...)

alt.Chart(...)

alt.Chart(...)

alt.Chart(...)

alt.Chart(...)

alt.Chart(...)

alt.Chart(...)

alt.Chart(...)

alt.Chart(...)

alt.Chart(...)

alt.Chart(...)

alt.Chart(...)

In [39]:
azalea_chart_dict = hole_charts[12].to_dict()

In [38]:
azalea_chart_dict["mark"]

'geoshape'

In [40]:
azalea_chart_dict

{'config': {'view': {'continuousWidth': 400, 'continuousHeight': 300},
  'legend': {'disable': True}},
 'data': {'name': 'data-23fe2ac199a5ea6854b49c9051ac5f1b'},
 'mark': 'geoshape',
 'encoding': {'color': {'field': 'ground_cover',
   'scale': {'domain': ['water',
     'sand',
     'green',
     'short_grass',
     'woods',
     'long_grass'],
    'range': ['RoyalBlue',
     'Khaki',
     'Aquamarine',
     'LawnGreen',
     'ForestGreen',
     'LimeGreen']},
   'type': 'nominal'},
  'tooltip': [{'field': 'name', 'type': 'nominal'},
   {'field': 'ground_cover', 'type': 'nominal'},
   {'field': 'course_area', 'type': 'nominal'}]},
 'projection': {'reflectY': True, 'type': 'identity'},
 'title': '13 - Azalea',
 '$schema': 'https://vega.github.io/schema/vega-lite/v4.17.0.json',
 'datasets': {'data-23fe2ac199a5ea6854b49c9051ac5f1b': [{'name': 'rough',
    'course_area': 'general_area',
    'ground_cover': 'long_grass',
    'type': 'Feature',
    'geometry': {'type': 'Polygon',
     'coordinates': [[[-352.6182724139837, -967.6840509963104],
       [-354.6305554956713, -969.2001866296292],
       [-356.754651597599, -971.3591881964651],
       [-359.37674696429804, -974.1489128541585],
       [-361.4805377231845, -976.8416176228769],
       [-362.2225064577407, -979.303905938242],
       [-361.8771231101685, -983.7312306857918],
       [-360.7186687844664, -986.8121949293514],
       [-360.1089964100812, -989.626288585121],
       [-360.749367045427, -992.9497837466413],
       [-362.38569405750917, -996.2732446957463],
       [-362.90404481737863, -997.6438744057281],
       [-363.09719970515704, -999.4269225050825],
       [-362.6501190429354, -1001.852862692691],
       [-362.2030823120429, -1005.5645429986132],
       [-362.436966445615, -1009.6158293691026],
       [-363.026546150441, -1013.5579368639475],
       [-373.99222928961973, -1013.181535550612],
       [-374.0529525857916, -1006.0250552848288],
       [-373.93076698793527, -999.4871922597712],
       [-373.16837495152066, -994.3806474919052],
       [-372.89381478936986, -989.7350111282129],
       [-372.8225101163326, -985.0651082991463],
       [-372.6190813850495, -980.1768768673751],
       [-372.71037906377467, -975.434190487276],
       [-372.95417298011415, -972.2319610042797],
       [-373.63498818533714, -969.636197264605],
       [-374.28532975191246, -967.4649714148626],
       [-375.5250996997722, -964.9298358165253],
       [-377.0798940965023, -961.8003372010504],
       [-377.7099310532067, -960.247722703462],
       [-379.6000936139116, -957.057563561829],
       [-382.0492309455343, -954.5102539603447],
       [-386.00243358992043, -951.3078891207384],
       [-388.4414110749931, -948.9182635113615],
       [-387.150715197908, -948.263311203985],
       [-385.9006652333694, -947.4628017502874],
       [-385.2908831454488, -947.0261575378364],
       [-384.6811064159611, -946.7350687881512],
       [-382.953431399281, -946.6138353852571],
       [-381.0123286544341, -946.2257576585005],
       [-378.2988622511016, -946.0196516706351],
       [-374.8740005079778, -945.7650517827813],
       [-372.0792253597805, -945.3648730838665],
       [-370.3108821894096, -944.7463244205296],
       [-366.67259073983405, -944.1399702340451],
       [-362.57698736110876, -943.8853896435764],
       [-358.05453074598415, -943.1213777041315],
       [-354.27395534481144, -942.3209500685903],
       [-349.7718231167994, -941.4841561462819],
       [-347.8812954181415, -941.0576358426343],
       [-351.80693438366444, -967.088179488296],
       [-352.6182724139837, -967.6840509963104]]]}},
   {'name': 'rough',
    'course_area': 'general_area',
    'ground_cover': 'long_grass',
    'type': 'Feature',
    'geometry': {'type': 'Polygon',
     'coordinates': [[[-420.59463466230744, -649.2788467984294],
       [-419.71042829349886, -647.5079560633673],
       [-418.6636408585819, -646.1979976360217],
       [-416.67174853709827, -645.0215023997183],
       [-413.958313682385, -643.6630906736369],
       [-411.3770115679668, -642.8141175488299],
       [-408.60265197422723, -642.7171883224847],
       [-404.94417709162923, -643.14186642222],
       [-402.07841297134956, -644.5611427176491],
       [-399.212657718496, -646.2351404576543],
       [-396.6924450485379, -648.418568880648],
       [-394.49744757638734, -651.0507808383094],
       [-393.1967183986088, -652.8945331108072],
       [-392.7902998203072, -655.0657519607074],
       [-392.78022629324005, -657.4552893754815],
       [-393.28844663339277, -660.0267519169668],
       [-394.0405562226275, -662.3070942098647],
       [-395.7987410105704, -664.2598987521678],
       [-398.573130895746, -665.0118313354068],
       [-403.09543694921797, -664.8782335977818],
       [-407.1197491898822, -663.9319679742632],
       [-411.23548061214893, -661.8940305913269],
       [-415.16827317967386, -659.5407284294358],
       [-417.60719436846756, -657.5998914363689],
       [-419.5989555420184, -655.4164790745242],
       [-420.7167372910907, -653.1118049232147],
       [-421.0012191228702, -651.4136454149976],
       [-420.59463466230744, -649.2788467984294]]]}},
   {'name': 'rough',
    'course_area': 'general_area',
    'ground_cover': 'long_grass',
    'type': 'Feature',
    'geometry': {'type': 'Polygon',
     'coordinates': [[[-394.0805671593951, -917.2839919752636],
       [-392.15978586417475, -916.6533230183767],
       [-389.5580721940107, -915.2342532186761],
       [-387.28155121237876, -913.3906339532451],
       [-385.6554358332561, -911.2680090525198],
       [-384.50695758330755, -908.8178666092846],
       [-384.61866406582584, -906.5253633038748],
       [-385.2690149807338, -904.7786734901406],
       [-385.9295253032303, -902.9470758815864],
       [-386.5595347771131, -900.7758498235294],
       [-387.7586350282584, -898.0223807902033],
       [-390.0654131510247, -893.7041489903771],
       [-393.0124380487866, -889.3252447021669],
       [-395.8273662179811, -885.5043073173638],
       [-396.7113933237958, -882.0837195959778],
       [-396.73156868348406, -878.09307187472],
       [-396.5281746919564, -874.3692843131216],
       [-396.1418222774917, -869.844948273261],
       [-394.9323681321113, -867.3462906137797],
       [-393.61115755530517, -865.7209700691077],
       [-391.62934470438074, -863.3436370652469],
       [-387.9096287594218, -858.6617387131312],
       [-385.46028555260403, -854.9259035497827],
       [-384.04758871982983, -852.6091964143818],
       [-383.71212375197507, -849.9528204202777],
       [-384.04736134346666, -846.3624387677968],
       [-385.99841280630443, -841.401350290136],
       [-388.63043674595264, -838.5022728967972],
       [-391.61815958765175, -835.7972556683808],
       [-393.98595508213344, -832.9952237356274],
       [-395.44925656209534, -829.7565586357539],
       [-396.70923522725036, -824.6863273030984],
       [-397.19690090934114, -820.9261246014262],
       [-397.33901626451916, -816.6322312865908],
       [-396.74941922554154, -812.2777173522089],
       [-394.73711554095354, -809.5728859793184],
       [-391.9829829962393, -808.0082667525606],
       [-389.49310346049066, -807.0865072966088],
       [-387.8060291187607, -804.9881439329475],
       [-387.16567871823133, -802.1377050449198],
       [-386.9928165897324, -799.4813230073632],
       [-387.0943369408975, -796.5944679740846],
       [-387.3177975556437, -793.4043677685046],
       [-388.1611500377562, -789.4622078557694],
       [-387.82565973373903, -786.0901837416164],
       [-386.04715486734807, -784.7923788189312],
       [-384.08574948965446, -784.2102282804528],
       [-383.7706370505528, -782.2452400789534],
       [-389.57334353217715, -778.3514169465076],
       [-393.3028196781303, -772.9778535069037],
       [-395.46730319530934, -768.9628658029569],
       [-400.79217554590105, -760.3142401863902],
       [-403.5558958407947, -747.1413587598156],
       [-408.4945123881046, -736.9280217158938],
       [-421.2484463349816, -734.7563167320334],
       [-443.4935400684919, -716.6943882437865],
       [-462.7208471223764, -711.4171740131894],
       [-487.883263289329, -710.6154849494188],
       [-498.0760381458621, -705.2415831206131],
       [-501.4086258361464, -690.0066112580382],
       [-508.60351415551986, -686.3431188701812],
       [-514.8737063738894, -684.6810555434191],
       [-525.7171966930001, -686.4029281422836],
       [-529.3147145309617, -686.1358964287999],
       [-533.0749911921109, -689.0104292154566],
       [-535.7681865220901, -691.5211260209658],
       [-538.7153663599448, -692.4670870162203],
       [-541.0324229464023, -692.4912277097886],
       [-543.8879782324617, -690.2834883938358],
       [-545.6561622163238, -688.4518230953607],
       [-548.3287800426732, -686.0500179590098],
       [-552.048162346475, -684.1576018434608],
       [-555.5541567169038, -682.7625104515774],
       [-558.6232012892531, -682.1073484184313],
       [-562.05809335732, -681.4036474947201],
       [-564.6799865970286, -680.7485075104183],
       [-567.9014108879253, -679.0380568734746],
       [-571.1430987402914, -676.2116782501406],
       [-573.9884530999337, -673.4944868575012],
       [-576.8134577776974, -670.3527587690611],
       [-579.1201293748892, -666.4105028262986],
       [-580.4411640698394, -664.7729302456124],
       [-582.2195347342962, -663.5719989323171],
       [-584.4247640288751, -662.9896547880726],
       [-587.2295957811249, -662.686258306429],
       [-591.4267122336396, -662.7951905280519],
       [-593.6421272383104, -662.6373809213428],
       [-596.0709168730936, -661.8124291690877],
       [-597.0362673061665, -660.2840412550429],
       [-597.3207188921918, -658.549488118934],
       [-596.6498634834688, -656.2327668142544],
       [-595.8875644891914, -654.243550626765],
       [-595.1862660100759, -652.703127238144],
       [-594.5561064868317, -651.1869590519584],
       [-594.4036104618192, -650.1438194860561],
       [-594.6779400627839, -649.1249151243679],
       [-595.9177107599681, -648.2029933059989],
       [-597.7367508411633, -647.4265940962856],
       [-599.8606884819362, -647.0625846547299],
       [-600.0944268950564, -647.0868306216177],
       [-602.1472574912245, -647.2565284769954],
       [-604.4948111961402, -647.6202831270872],
       [-607.0150686100833, -646.9651384142717],
       [-609.4234971039429, -645.5943513995081],
       [-611.445703747242, -643.4109010182756],
       [-612.6548595045979, -640.3299048769953],
       [-612.5733012516724, -635.8783354116723],
       [-611.7702671575915, -632.445696707486],
       [-610.4388809937551, -630.6627182046363],
       [-609.0668594368406, -629.1223344763665],
       [-608.7212370360488, -627.4120765755325],
       [-608.8633609858216, -624.8041978895709],
       [-608.7920907907303, -622.499572262446],
       [-608.4362901080628, -620.5103334274975],
       [-607.5723990804642, -619.0790868429892],
       [-606.39344650107, -617.1990619750499],
       [-605.3059487281116, -615.1856057913313],
       [-602.5009950461584, -613.123729188542],
       [-600.1534256282777, -612.3475666476792],
       [-597.6839319448878, -612.008077186743],
       [-595.2449572395999, -612.2265484223622],
       [-592.948237592619, -612.1053814486586],
       [-591.7286991690023, -611.3048943125237],
       [-587.8564567547293, -605.0098325810064],
       [-587.4599669589744, -602.2321692761636],
       [-588.0085864210242, -599.5029718339949],
       [-564.7368069549029, -603.131002743082],
       [-566.0886909848103, -608.3466714007773],
       [-566.5462477588925, -612.9437767643115],
       [-565.4082636799096, -616.8617084114964],
       [-559.8699971576027, -621.9321892131339],
       [-557.5632915591113, -625.1830522638384],
       [-556.2830763155841, -630.010712634852],
       [-553.5495868947634, -634.0742824767567],
       [-548.7327761748759, -637.8953675528842],
       [-542.798091013607, -641.7407672398868],
       [-541.6803838446245, -644.9551766006625],
       [-542.036226355102, -647.9875657804492],
       [-543.1542934265734, -651.7598231363731],
       [-544.8414217798205, -654.7800139432786],
       [-546.5183483962528, -657.0239086996658],
       [-547.6160684867186, -660.3231110374065],
       [-547.5654115187513, -663.3191321709791],
       [-546.1225073294293, -666.6063365610106],
       [-542.72839380737, -669.7359561090376],
       [-540.0557695277181, -671.9558154382058],
       [-537.921784759816, -674.7214799574334],
       [-535.3304810451689, -677.3901302137346],
       [-532.607066432278, -680.1194346406563],
       [-529.0909469317385, -682.3029448221772],
       [-524.843002352634, -682.0241755211905],
       [-521.1945863506235, -680.5324119866631],
       [-517.3531520847729, -680.4355640201288],
       [-512.5767662154813, -680.3266304905367],
       [-507.6987967743726, -681.078903367238],
       [-504.06073495439017, -683.5413925414415],
       [-501.07308117830183, -686.1857940197668],
       [-498.20737385245735, -688.7816703702432],
       [-494.93511813227207, -690.3950650557441],
       [-492.0592744816156, -693.6095512784874],
       [-489.3663855178926, -697.4911578124426],
       [-484.51899266925193, -700.3903628578411],
       [-478.88905286802645, -702.6467308836626],
       [-473.05581862095806, -703.9812532197217],
       [-468.07622137453495, -704.9882345108693],
       [-462.4767169618629, -706.1893147042],
       [-455.7085089492715, -707.1478498923781],
       [-449.0114591589106, -708.6158221175336],
       [-444.24532695193733, -710.9570422329374],
       [-439.91616530940604, -712.8979642292865],
       [-435.51587627514925, -715.1299984684292],
       [-431.59326827789215, -718.4172890295446],
       [-428.1279923434246, -722.1897447112299],
       [-423.08755865875264, -726.9811513141237],
       [-417.8641625878048, -730.9720072479649],
       [-412.3459609712877, -732.7310204784461],
       [-408.5045298364508, -733.1799661633445],
       [-405.88265680444493, -734.9509930952456],
       [-403.97220895974345, -737.934954990866],
       [-402.11261726229975, -742.0833589011866],
       [-400.3648115104295, -746.2074989651685],
       [-399.25722805964875, -749.834299754425],
       [-398.7492769946569, -754.54061466157],
       [-397.16404094978134, -757.9127110454721],
       [-393.90202549822385, -762.5948697268182],
       [-390.86358649749974, -767.3376672277647],
       [-386.8393623256761, -771.8015185754248],
       [-383.71957607996586, -775.4283911930198],
       [-381.5144148449758, -778.8490261693416],
       [-380.45764503434106, -782.7669340508276],
       [-379.4213571325319, -791.063636594277],
       [-378.73062302242397, -800.0881041865379],
       [-378.63933349672993, -804.9399583706208],
       [-378.64967547504733, -809.9373644040984],
       [-379.21890650038534, -813.370028436732],
       [-380.3369263114613, -816.9603578052946],
       [-380.0524465741808, -819.0224046500667],
       [-379.0870663050274, -820.9995685793118],
       [-377.0952698203562, -823.3042690750873],
       [-374.02623267709055, -825.6453963130645],
       [-370.20516331451034, -828.1442342136394],
       [-366.25198392353417, -830.8250197110456],
       [-362.5223914444328, -833.8090367055447],
       [-358.58954773138936, -836.9143555463547],
       [-356.3131948845685, -839.3888765120666],
       [-355.1852293189673, -842.0695620338548],
       [-355.06334670077365, -844.131602660159],
       [-355.51056995901104, -846.0844574806729],
       [-356.13055391534505, -847.8917509289402],
       [-357.4212799675168, -849.8567067789182],
       [-360.0738068605039, -851.8701345869079],
       [-364.9214482343736, -853.1557084429033],
       [-370.0028370970346, -854.5746977664904],
       [-375.5009378214357, -857.1338546994342],
       [-379.24088241114106, -859.2927944308468],
       [-382.80809014864224, -862.203775928786],
       [-385.0541378002062, -864.7751749729758],
       [-386.8733921807885, -868.4018666687758],
       [-388.0727050423208, -871.5312661813863],
       [-388.1032738868263, -873.7267273871261],
       [-388.06273417822837, -876.7470057768547],
       [-387.81891406580644, -879.0516436914555],
       [-387.2193969335528, -881.2956465252804],
       [-386.4775918664825, -883.2728027592683],
       [-385.207338049661, -885.5896077662304],
       [-381.23400222127725, -893.4376200148602],
       [-376.71192402479005, -902.7048164930682],
       [-373.35849788008977, -910.4315071883418],
       [-370.2286037074279, -916.920967106141],
       [-369.48676661847185, -918.1460852760302],
       [-368.4400348125909, -919.0194549073092],
       [-366.8953120033516, -919.419786372221],
       [-365.1473220560743, -919.4683655132334],
       [-358.14517795353316, -919.0319389974973],
       [-348.23645921809407, -917.649493385262],
       [-340.5127350910866, -916.364005180725],
       [-331.18328960747266, -914.7389323293256],
       [-322.9514258233321, -913.2229843187238],
       [-313.93703095396893, -911.6100161899233],
       [-302.3412890354006, -909.4512814913892],
       [-291.0504334380437, -907.2803960125497],
       [-288.1946823655775, -906.4071413594269],
       [-285.02388095294134, -905.3034315613797],
       [-282.67362693230876, -904.090485430197],
       [-282.3922518200643, -908.0244268452792],
       [-282.3479481537391, -909.9673438807198],
       [-282.4585806377253, -911.4513812947259],
       [-290.5830908178074, -912.4718886189165],
       [-310.6139206868938, -915.1398355541007],
       [-320.68524333348023, -916.7649040688351],
       [-332.4029487952449, -918.8872258707453],
       [-345.26906367977847, -921.4582932738941],
       [-353.68384984592126, -922.4769030885155],
       [-360.03559193430885, -923.2529842843833],
       [-366.66175187389354, -924.6840518877541],
       [-373.03385476067336, -926.3941056950621],
       [-387.65819368634686, -930.299317853232],
       [-390.00580341004496, -930.6752497210235],
       [-391.87401581297974, -930.7366915382459],
       [-394.08675281855017, -917.2888676974711],
       [-394.0805671593951, -917.2839919752636]]]}},
   {'name': 'rough',
    'course_area': 'general_area',
    'ground_cover': 'long_grass',
    'type': 'Feature',
    'geometry': {'type': 'Polygon',
     'coordinates': [[[-556.7588122497287, -594.0099445669083],
       [-558.8321982547944, -598.7403908933537],
       [-564.7368069549029, -603.131002743082],
       [-588.0085864210242, -599.5029718339949],
       [-589.0450334545379, -597.3317101401669],
       [-590.0713250930858, -595.2938748407778],
       [-590.9045071059816, -592.8436428121092],
       [-591.0156235462746, -592.4472583820975],
       [-588.1718119102179, -592.0769096546633],
       [-586.9726367788408, -591.9799391223577],
       [-586.5967954105171, -591.9708549831126],
       [-586.2005140213257, -591.8506443379262],
       [-576.4459979205193, -590.8899083580877],
       [-556.169709959023, -592.7882620845945],
       [-556.7588122497287, -594.0099445669083]]]}},
   {'name': 'rough',
    'course_area': 'general_area',
    'ground_cover': 'long_grass',
    'type': 'Feature',
    'geometry': {'type': 'Polygon',
     'coordinates': [[[-290.530281176881, -839.9852446776835],
       [-295.33729291870725, -842.5202031828815],
       [-301.1503891814071, -844.2788347233345],
       [-306.9532936564431, -844.9700562133518],
       [-312.03462486041894, -844.8364812703227],
       [-316.38418913609297, -842.883481857651],
       [-318.77232896460333, -839.99655883708],
       [-320.2458035433287, -836.3091077035356],
       [-321.3228972123073, -831.4329649990389],
       [-321.41397942858873, -818.903057638402],
       [-320.9766926946961, -809.2721470501766],
       [-320.2140694430566, -795.2503210998756],
       [-320.6204173173755, -790.0830874765868],
       [-321.87027420719807, -785.3282354406466],
       [-324.9595523565844, -780.257956413968],

In [22]:
augusta_national.gdf

,name,course_area,ground_cover,geometry
168,woods,general_area,woods,"POLYGON ((-364.377 210.856, -364.295 207.363, ..."
222,rough,general_area,long_grass,"POLYGON ((-399.804 -688.022, -398.869 -692.801..."
158,woods,general_area,woods,"POLYGON ((-167.382 -395.922, -159.639 -418.350..."
138,fairway,general_area,short_grass,"POLYGON ((-106.194 -302.804, -105.249 -314.509..."
135,fairway,general_area,short_grass,"POLYGON ((-181.484 -183.993, -181.413 -186.310..."
...,...,...,...,...
112,tee,teeing_area,short_grass,"POLYGON ((-183.500 -421.879, -177.088 -422.219..."
34,bunkers,bunker,sand,"POLYGON ((-94.679 -80.650, -94.435 -81.656, -9..."
161,woods,general_area,woods,"POLYGON ((-245.263 -280.750, -230.011 -333.381..."
32,bunkers,bunker,sand,"POLYGON ((-179.462 -186.079, -179.370 -186.953..."
31,bunkers,bunker,sand,"POLYGON ((-173.079 -166.866, -173.039 -167.715..."